name: F1_venv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - tensorflow==1.15.0
  - fastf1
  - numpy=1.20.3
  - pandas=1.2.4
  - matplotlib=3.4.2
  - seaborn=0.11.1
  - hydra-core==1.3.2
  - omegaconf==2.3.0
  - penpyxl==3.1.2
  - statsmodels==0.14.0

tqdm>=4.36.1
argparse>=1.1
pandas>=0.25.1
scikit-learn>=0.21.3
matplotlib>=3.1.1
protobuf==3.20.3