name: F1_venv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - tensorflow=2.7.0
  - fastf1
  - numpy=1.20.3
  - pandas=1.2.4
  - matplotlib=3.4.2
  - seaborn=0.11.1
  - hydra-core==1.3.2
  - omegaconf==2.3.0
  - penpyxl==3.1.2